name: Minify Userscript

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Minify:
    name: Minify userscript
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Install Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version-file: ".node-version"
      - name: Minify
        run: |
          echo "Minifying userscript..."
          sed -n '/\/\/ ==UserScript==/,/\/\/ ==\/UserScript==/p' "dist/Hagezi to NextDNS.user.js" > "meta.js"
          sed -n '/\/\/ ==\/UserScript==/,$p' "dist/Hagezi to NextDNS.user.js" | tail -n +2 > "input.js"
          npx terser --compress --mangle --comments false --parse bare_returns --output "output.js" -- "input.js"
          [ $(wc -c < "output.js") -lt 100 ] && { echo "Failed to minify userscript"; exit 1; }
          cat "meta.js" "output.js" > "dist/Hagezi to NextDNS.min.user.js"
          echo "Userscript minification completed!"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: main
          file_pattern: "dist/*.min.user.js"
          commit_message: minify userscript
